### ISSUE TITLE
Upgrade nanoc version to fix error running nanoc view

### ISSUE THREAD

**Issue by MaxPhilips** [cerner/fhir.cerner.com#285]
According to https://github.com/nanoc/nanoc/issues/1441 we need nanoc 4.11.6+ to get a fix for this error:

```
$ nanoc view

Captain! We’ve been hit!

KeyError: key not found: :host

  0. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/nanoc-4.9.6/lib/nanoc/cli/commands/view.rb:34:in `fetch'
  1. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/nanoc-4.9.6/lib/nanoc/cli/commands/view.rb:34:in `run'
  2. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/nanoc-4.9.6/lib/nanoc/cli/command_runner.rb:14:in `block in call'
  3. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/nanoc-4.9.6/lib/nanoc/cli/error_handler.rb:15:in `block in handle_while'
  4. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/nanoc-4.9.6/lib/nanoc/cli/error_handler.rb:57:in `handle_while'
  5. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/nanoc-4.9.6/lib/nanoc/cli/error_handler.rb:15:in `handle_while'
  6. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/nanoc-4.9.6/lib/nanoc/cli/command_runner.rb:13:in `call'
  7. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/cri-2.15.9/lib/cri/command_dsl.rb:303:in `block in runner'
  8. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/cri-2.15.9/lib/cri/command.rb:360:in `run_this'
  9. /Users/mp028833/.rvm/gems/ruby-2.3.1@fhir.cerner.com/gems/cri-2.15.9/lib/cri/command.rb:296:in `run'
  ... 11 lines omitted (see crash.log for details)

A detailed crash log has been written to ./crash.log.
```

That version or higher of nanoc will require a ruby upgrade from 2.3.1 to at least 2.4

**Comment by ebaranowski** [comment]
I created a PR for this change: https://github.com/cerner/fhir.cerner.com/pull/290

**Comment by MaxPhilips** [comment]
closed via PR 290
